apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-prod.yaml
    path: apps/my-cool-helm-app
    repoURL: https://github.com/Nico-Hab/argo-test.git
    targetRevision: main
