apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cool-application
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-cool-application
          image: localhost:32000/hello-world:v1