apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cool-product
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-dev.yaml
    path: apps/my-cool-helm-app
    repoURL: https://github.com/Nico-Hab/argo-test.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true