apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cool-product
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/my-cool-kustomize-app/dev
    repoURL: https://github.com/Nico-Hab/argo-test.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true